# Generated by Django 4.0.6 on 2022-08-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baloosh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrivaldates', models.CharField(max_length=200)),
                ('departuredates', models.CharField(max_length=200)),
                ('adults', models.CharField(max_length=200)),
                ('children', models.CharField(max_length=200)),
                ('noofrooms', models.CharField(max_length=200)),
                ('roomtypes', models.CharField(max_length=200)),
                ('amounts', models.CharField(max_length=200)),
            ],
        ),
    ]
