# Generated by Django 4.0.6 on 2022-08-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baloosh', '0003_bookings_delete_reservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='amounts',
            field=models.IntegerField(),
        ),
    ]
