# Generated by Django 4.0.6 on 2022-08-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baloosh', '0004_alter_bookings_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='noofrooms',
            field=models.IntegerField(max_length=200),
        ),
    ]
