# Generated by Django 4.0.6 on 2022-08-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baloosh', '0005_alter_bookings_noofrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='noofrooms',
            field=models.IntegerField(),
        ),
    ]
