# Generated by Django 4.0.6 on 2022-08-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baloosh', '0006_alter_bookings_noofrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='amounts',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='noofrooms',
            field=models.CharField(max_length=200),
        ),
    ]
